# Generated by Django 5.2.17 on 2026-09-11 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanupJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('done', 'done'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='pending', max_length=12)),
                ('dry_run', models.BooleanField(default=False)),
                ('reddit_username', models.CharField(blank=True, max_length=64)),
                ('options', models.JSONField(default=dict)),
                ('submissions_seen', models.IntegerField(default=0)),
                ('submissions_deleted', models.IntegerField(default=0)),
                ('comments_seen', models.IntegerField(default=0)),
                ('comments_deleted', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('current', models.CharField(blank=True, max_length=200)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('cancel_requested', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
